// src/pages/projects/projects.component.ts
import { Component, ChangeDetectionStrategy, signal, computed } from '@angular/core';

interface Project {
  title: string;
  image: string;
  tags: string[];
  description: string;
  repoUrl: string;
  categories: string[];
}

@Component({
  selector: 'app-projects',
  templateUrl: './projects.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ProjectsComponent {
  
  readonly filters = ['all', 'genai', 'full-stack', 'machine-learning', 'deep-learning', 'nlp'];
  activeFilter = signal('all');

  projects = signal<Project[]>([
    {
      title: 'RecipePro.ai',
      image: 'recipe.png',
      tags: ['Django', 'LangChain', 'Gemini'],
      description: 'AI-powered recipe generator using Google Generative AI and LangChain for personalized cooking experiences.',
      repoUrl: 'https://github.com/Rahul4112002/RecipePro.ai',
      categories: ['genai', 'full-stack']
    },
    {
      title: 'CareerVision.ai',
      image: 'career.png',
      tags: ['Django', 'ML', 'Adzuna API'],
      description: 'Career prediction platform using ML to suggest suitable jobs and real-time listings based on user inputs.',
      repoUrl: 'https://github.com/Rahul4112002/CareerVision.ai',
      categories: ['machine-learning', 'full-stack']
    },
    {
      title: 'StockVision',
      image: 'stock.png',
      tags: ['Django', 'LSTM', 'Yahoo API'],
      description: 'Real-time stock trend forecasting platform using LSTM models and interactive chart visualizations.',
      repoUrl: 'https://github.com/Rahul4112002/StockVision',
      categories: ['deep-learning', 'full-stack']
    },
    {
      title: 'Parkinsons Detection',
      image: 'https://raw.githubusercontent.com/Rahul4112002/my-portfolio/main/parkinsons.png',
      tags: ['ML', 'Classification'],
      description: "ML model for detecting Parkinson's disease using multiple classification algorithms.",
      repoUrl: 'https://github.com/Rahul4112002/Parkinsons--Diseases-Detection',
      categories: ['machine-learning']
    },
    {
      title: 'Fake News Detection',
      image: 'news.png',
      tags: ['NLP', 'ML'],
      description: 'Harnesses ML techniques to classify news articles as real or fake.',
      repoUrl: 'https://github.com/Rahul4112002/Fake-News-Detection',
      categories: ['machine-learning', 'nlp']
    },
    {
      title: 'Credit Card Fraud Detection',
      image: 'card.png',
      tags: ['Random Forest'],
      description: 'ML model to detect fraud in credit card transactions using Random Forest.',
      repoUrl: 'https://github.com/Rahul4112002/CREDIT-CARD-FRAUD-DETECTION',
      categories: ['machine-learning']
    },
    {
      title: 'Customer Churn Prediction',
      image: 'churn.png',
      tags: ['Random Forest'],
      description: 'Predicting whether bank customers will stay or leave using Random Forest.',
      repoUrl: 'https://github.com/Rahul4112002/Customer-Churn-Prediction',
      categories: ['machine-learning']
    },
    {
      title: 'Forest Fire Prediction',
      image: 'fire.png',
      tags: ['ML', 'Predictive Modeling'],
      description: 'Predictive model to forecast forest fire occurrences based on environmental factors.',
      repoUrl: 'https://github.com/Rahul4112002/Forest-Fire-Precition',
      categories: ['machine-learning']
    },
    {
      title: 'Diabetes Prediction',
      image: 'diabetes.png',
      tags: ['Healthcare', 'Classification'],
      description: 'ML project that predicts whether a patient is diabetic based on health parameters.',
      repoUrl: 'https://github.com/Rahul4112002/Diabetes-Prediction',
      categories: ['machine-learning']
    }
  ]);
  
  filteredProjects = computed(() => {
    const filter = this.activeFilter();
    if (filter === 'all') {
      return this.projects();
    }
    return this.projects().filter(p => p.categories.includes(filter));
  });

  setFilter(filter: string) {
    this.activeFilter.set(filter);
  }
}

<section id="projects" class="projects py-20 min-h-screen">
    <div class="container mx-auto px-6">
        <div class="section-header text-center mb-12">
            <h2 class="text-4xl font-bold">My Projects</h2>
            <div class="underline"></div>
        </div>
        <div class="projects-filter flex flex-wrap justify-center gap-2 md:gap-4 mb-10">
            @for(filter of filters; track filter) {
                <button 
                    (click)="setFilter(filter)"
                    [class]="activeFilter() === filter ? 'primary-btn text-white' : 'secondary-btn'"
                    class="px-4 py-2 rounded-full text-sm capitalize">
                    {{ filter.replace('-', ' ') }}
                </button>
            }
        </div>

        <div class="projects-grid grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            @for(project of filteredProjects(); track project.title) {
                <div class="project-card rounded-lg">
                    <div class="project-img overflow-hidden h-56">
                      <img [src]="project.image" [alt]="project.title" class="w-full h-full object-cover">
                    </div>
                    <div class="p-6">
                        <h3 class="text-2xl font-bold mb-2">{{ project.title }}</h3>
                        <div class="flex flex-wrap gap-2 mb-4">
                            @for(tag of project.tags; track tag) {
                                <span class="bg-gray-700 text-xs px-2 py-1 rounded">{{ tag }}</span>
                            }
                        </div>
                        <p class="text-gray-400 mb-4">{{ project.description }}</p>
                        <a [href]="project.repoUrl" target="_blank" class="primary-btn text-white text-sm font-bold py-2 px-4 rounded-full inline-block">
                            <i class="fab fa-github"></i> Source Code
                        </a>
                    </div>
                </div>
            }
        </div>
    </div>
</section>

// src/data/projects.tsx
import { Icons } from "@/components/icons";

export type ProjectCategory = "All" | "Gen AI" | "Full Stack" | "Machine Learning" | "Deep Learning" | "NLP";

export interface Project {
  title: string;
  href: string;
  dates: string;
  active: boolean;
  description: string;
  technologies: string[];
  links: {
    type: string;
    href: string;
    icon: React.ReactNode;
  }[];
  image: string;
  category: ProjectCategory[];
}

export const allProjects: Project[] = [
  {
    title: "CareerVision.ai",
    href: "https://github.com/Rahul4112002/CareerVision.ai",
    dates: "2024",
    active: true,
    description: "Career prediction platform using ML to suggest suitable jobs and real-time listings based on user inputs using Adzuna API.",
    technologies: ["Django", "Machine Learning", "Adzuna API", "Python"],
    links: [
      {
        type: "Source",
        href: "https://github.com/Rahul4112002/CareerVision.ai",
        icon: <Icons.github className="size-3" />,
      },
    ],
    image: "/projects/careervision.png",
    category: ["Machine Learning", "Full Stack"],
  },
  {
    title: "Advanced AI Chatbot with Multi-Tool Integration",
    href: "https://github.com/Rahul4112002/Advanced-AI-Chatbot-with-Multi-Tool-Integration-using-LangGraph",
    dates: "2024",
    active: true,
    description: "AI chatbot using Groq Llama-3.1-8B with 95% tool accuracy and SQLite chat persistence.",
    technologies: ["Python", "LangGraph", "LangChain", "Streamlit", "Groq", "SQLite"],
    links: [
      {
        type: "Source",
        href: "https://github.com/Rahul4112002/Advanced-AI-Chatbot-with-Multi-Tool-Integration-using-LangGraph",
        icon: <Icons.github className="size-3" />,
      },
    ],
    image: "/projects/aichatbot.png",
    category: ["Gen AI", "Full Stack"],
  },
  {
    title: "Car Price Prediction API",
    href: "https://github.com/Rahul4112002/car-price-prediction-api",
    dates: "2024",
    active: true,
    description: "ML-powered REST API with FastAPI predicting car prices with 85%+ accuracy and Redis caching.",
    technologies: ["Python", "FastAPI", "Machine Learning", "Docker", "Redis", "Prometheus"],
    links: [
      {
        type: "Source",
        href: "https://github.com/Rahul4112002/car-price-prediction-api",
        icon: <Icons.github className="size-3" />,
      },
    ],
    image: "/projects/carpriceprediction.png",
    category: ["Machine Learning", "Full Stack"],
  },
  {
    title: "RecipePro.ai",
    href: "https://github.com/Rahul4112002/RecipePro.ai",
    dates: "2024",
    active: true,
    description: "AI-powered recipe generator using Google Generative AI and LangChain for personalized cooking experiences.",
    technologies: ["Django", "LangChain", "Gemini", "Python"],
    links: [
      {
        type: "Source",
        href: "https://github.com/Rahul4112002/RecipePro.ai",
        icon: <Icons.github className="size-3" />,
      },
    ],
    image: "/projects/recipepro.png",
    category: ["Gen AI", "Full Stack"],
  },
  {
    title: "Conversational AI Chatbot with Google Gemini",
    href: "https://github.com/Rahul4112002/Conversational-AI-Chatbot-with-Google-Gemini",
    dates: "2024",
    active: true,
    description: "Flask-based chatbot powered by Gemini API with SQLite database, real-time responses, and purple-gradient UI.",
    technologies: ["Flask", "Google Gemini", "GenAI"],
    links: [
      {
        type: "Source",
        href: "https://github.com/Rahul4112002/Conversational-AI-Chatbot-with-Google-Gemini",
        icon: <Icons.github className="size-3" />,
      },
    ],
    image: "/projects/Conversational AI Chatbot with Google Gemini.png",
    category: ["Gen AI", "Full Stack"],
  },
  {
    title: "StockVision",
    href: "https://github.com/Rahul4112002/StockVision",
    dates: "2024",
    active: true,
    description: "Real-time stock trend forecasting platform using LSTM models and interactive chart visualizations.",
    technologies: ["Django", "LSTM", "Yahoo API"],
    links: [
      {
        type: "Source",
        href: "https://github.com/Rahul4112002/StockVision",
        icon: <Icons.github className="size-3" />,
      },
    ],
    image: "/projects/StockVision.png",
    category: ["Deep Learning", "Full Stack"],
  },
  {
    title: "Parkinsons Detection",
    href: "https://github.com/Rahul4112002/Parkinsons--Diseases-Detection",
    dates: "2024",
    active: true,
    description: "ML model for detecting Parkinson's disease using multiple classification algorithms.",
    technologies: ["Machine Learning", "Classification"],
    links: [
      {
        type: "Source",
        href: "https://github.com/Rahul4112002/Parkinsons--Diseases-Detection",
        icon: <Icons.github className="size-3" />,
      },
    ],
    image: "/projects/Parkinsons Detection.png",
    category: ["Machine Learning"],
  },
  {
    title: "Fake News Detection",
    href: "https://github.com/Rahul4112002/Fake-News-Detection",
    dates: "2024",
    active: true,
    description: "Harnesses ML techniques to classify news articles as real or fake.",
    technologies: ["NLP", "Machine Learning"],
    links: [
      {
        type: "Source",
        href: "https://github.com/Rahul4112002/Fake-News-Detection",
        icon: <Icons.github className="size-3" />,
      },
    ],
    image: "/projects/Smart ML classifier for identifying real vs fake news..png",
    category: ["NLP", "Machine Learning"],
  },
  {
    title: "Credit Card Fraud Detection",
    href: "https://github.com/Rahul4112002/CREDIT-CARD-FRAUD-DETECTION",
    dates: "2024",
    active: true,
    description: "ML model to detect fraud in credit card transactions using Random Forest.",
    technologies: ["Random Forest", "Machine Learning"],
    links: [
      {
        type: "Source",
        href: "https://github.com/Rahul4112002/CREDIT-CARD-FRAUD-DETECTION",
        icon: <Icons.github className="size-3" />,
      },
    ],
    image: "/projects/Detect fraudulent transactions instantly with machine learning..png",
    category: ["Machine Learning"],
  },
  {
    title: "Customer Churn Prediction",
    href: "https://github.com/Rahul4112002/Customer-Churn-Prediction",
    dates: "2024",
    active: true,
    description: "Predicting whether bank customers will stay or leave using Random Forest.",
    technologies: ["Random Forest", "Machine Learning"],
    links: [
      {
        type: "Source",
        href: "https://github.com/Rahul4112002/Customer-Churn-Prediction",
        icon: <Icons.github className="size-3" />,
      },
    ],
    image: "/projects/Accurate churn prediction using machine learning.png",
    category: ["Machine Learning"],
  },
  {
    title: "RAG Application with LangChain",
    href: "https://github.com/Rahul4112002/RAG-Application-with-LangChain",
    dates: "2024",
    active: true,
    description: "A Retrieval-Augmented Generation (RAG) application built with LangChain for enhanced document querying.",
    technologies: ["LangChain", "RAG"],
    links: [
      {
        type: "Source",
        href: "https://github.com/Rahul4112002/RAG-Application-with-LangChain",
        icon: <Icons.github className="size-3" />,
      },
    ],
    image: "/projects/RAG Application with LangChain.png",
    category: ["Gen AI"],
  },
  {
    title: "Web Scraper using LangChain",
    href: "https://github.com/Rahul4112002/Web-Scrapper-Using-Langchain",
    dates: "2024",
    active: true,
    description: "LangChain web-scraper that extracts, cleans, and embeds web content to power retrieval-augmented generation (RAG) for LLM-backed QA and summarization.",
    technologies: ["LangChain", "RAG", "Web Scraping"],
    links: [
      {
        type: "Source",
        href: "https://github.com/Rahul4112002/Web-Scrapper-Using-Langchain",
        icon: <Icons.github className="size-3" />,
      },
    ],
    image: "/projects/Web Scraper using LangChain.png",
    category: ["Gen AI", "NLP"],
  },
  {
    title: "Forest Fire Prediction",
    href: "https://github.com/Rahul4112002/Forest-Fire-Precition",
    dates: "2024",
    active: true,
    description: "Predictive model to forecast forest fire occurrences based on environmental factors.",
    technologies: ["Machine Learning", "Predictive Modeling"],
    links: [
      {
        type: "Source",
        href: "https://github.com/Rahul4112002/Forest-Fire-Precition",
        icon: <Icons.github className="size-3" />,
      },
    ],
    image: "/projects/Forest Fire Prediction.png",
    category: ["Machine Learning"],
  },
  {
    title: "Diabetes Prediction",
    href: "https://github.com/Rahul4112002/Diabetes-Prediction",
    dates: "2024",
    active: true,
    description: "ML project that predicts whether a patient is diabetic based on health parameters.",
    technologies: ["Healthcare", "Classification"],
    links: [
      {
        type: "Source",
        href: "https://github.com/Rahul4112002/Diabetes-Prediction",
        icon: <Icons.github className="size-3" />,
      },
    ],
    image: "/projects/Diabetes Prediction.png",
    category: ["Machine Learning"],
  },
];

export const projectCategories: ProjectCategory[] = ["All", "Gen AI", "Full Stack", "Machine Learning", "Deep Learning", "NLP"];
